guid: 112643
desc: 0
icon: data/ui/2kimages/main/3dicons/resident/icon_resident_colony03_tier02.png
name: Arctic Population 2
id: !<tag:yaml.org,2002:js/undefined> ''
template: PopulationLevel7
populationLevel7:
  populationInputs:
    - product: 114890
      amount: !<tag:yaml.org,2002:js/undefined> ''
      supplyWeight: 4
      moneyValue: 20
      fullWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
      noWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
    - product: 112705
      amount: 0.0004
      supplyWeight: 3
      moneyValue: 40
      fullWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
      noWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
    - product: 112702
      amount: 0.0002
      supplyWeight: 3
      moneyValue: 70
      fullWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
      noWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
    - product: 112693
      amount: !<tag:yaml.org,2002:js/undefined> ''
      supplyWeight: 3
      moneyValue: 30
      fullWeightPopulationCount: 300
      noWeightPopulationCount: 99
    - product: 1010217
      amount: 0.0002
      supplyWeight: 3
      moneyValue: 50
      fullWeightPopulationCount: 750
      noWeightPopulationCount: 299
    - product: 112703
      amount: 0.0003
      supplyWeight: 4
      moneyValue: 80
      fullWeightPopulationCount: 750
      noWeightPopulationCount: 749
    - product: 112708
      amount: !<tag:yaml.org,2002:js/undefined> ''
      supplyWeight: !<tag:yaml.org,2002:js/undefined> ''
      moneyValue: !<tag:yaml.org,2002:js/undefined> ''
      fullWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
      noWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
    - product: 112701
      amount: 0.0003
      supplyWeight: !<tag:yaml.org,2002:js/undefined> ''
      moneyValue: 50
      fullWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
      noWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
    - product: 1010216
      amount: 0.0005
      supplyWeight: !<tag:yaml.org,2002:js/undefined> ''
      moneyValue: 35
      fullWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
      noWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
    - product: 112700
      amount: 0.0004
      supplyWeight: !<tag:yaml.org,2002:js/undefined> ''
      moneyValue: 45
      fullWeightPopulationCount: 750
      noWeightPopulationCount: 299
    - product: 120032
      amount: 0.0004
      supplyWeight: !<tag:yaml.org,2002:js/undefined> ''
      moneyValue: 60
      fullWeightPopulationCount: 750
      noWeightPopulationCount: 749
  populationOutputs:
    - product: 112654
      amount: 100
  categoryIcon: data/ui/2kimages/main/icons/icon_arrow.png
  moodText:
    Angry: 116348
    Unhappy: 116348
    Neutral: 116016
    Happy: 112802
    Euphoric: 116017
