guid: 15000006
desc: 0
icon: data/ui/2kimages/main/3dicons/resident/icon_resident_obrera.png
name: Colony01 Population 2
id: !<tag:yaml.org,2002:js/undefined> ''
template: PopulationLevel7
populationLevel7:
  populationInputs:
    - product: 120020
      amount: !<tag:yaml.org,2002:js/undefined> ''
      supplyWeight: 5
      moneyValue: !<tag:yaml.org,2002:js/undefined> ''
      fullWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
      noWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
    - product: 120033
      amount: 0.000952381
      supplyWeight: 3
      moneyValue: 25
      fullWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
      noWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
    - product: 1010257
      amount: 0.000476191
      supplyWeight: !<tag:yaml.org,2002:js/undefined> ''
      moneyValue: 25
      fullWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
      noWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
    - product: 120043
      amount: 0.000833333
      supplyWeight: 2
      moneyValue: 25
      fullWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
      noWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
    - product: 120050
      amount: !<tag:yaml.org,2002:js/undefined> ''
      supplyWeight: !<tag:yaml.org,2002:js/undefined> ''
      moneyValue: !<tag:yaml.org,2002:js/undefined> ''
      fullWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
      noWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
    - product: 120035
      amount: 0.00047619
      supplyWeight: 4
      moneyValue: 10
      fullWeightPopulationCount: 300
      noWeightPopulationCount: !<tag:yaml.org,2002:js/undefined> ''
    - product: 120032
      amount: 0.000196079
      supplyWeight: 2
      moneyValue: 10
      fullWeightPopulationCount: 600
      noWeightPopulationCount: 299
    - product: 1010348
      amount: !<tag:yaml.org,2002:js/undefined> ''
      supplyWeight: !<tag:yaml.org,2002:js/undefined> ''
      moneyValue: 10
      fullWeightPopulationCount: 600
      noWeightPopulationCount: 299
    - product: 120037
      amount: 0.000444444
      supplyWeight: 2
      moneyValue: 10
      fullWeightPopulationCount: 1000
      noWeightPopulationCount: 599
    - product: 1010214
      amount: 0.000444444
      supplyWeight: !<tag:yaml.org,2002:js/undefined> ''
      moneyValue: 30
      fullWeightPopulationCount: 1000
      noWeightPopulationCount: 599
    - product: 1010259
      amount: 0.000185185
      supplyWeight: !<tag:yaml.org,2002:js/undefined> ''
      moneyValue: 35
      fullWeightPopulationCount: 1500
      noWeightPopulationCount: 999
    - product: 1010206
      amount: 0.000416667
      supplyWeight: 2
      moneyValue: 25
      fullWeightPopulationCount: 1500
      noWeightPopulationCount: 999
  populationOutputs:
    - product: 1010367
      amount: 100
  categoryIcon: !<tag:yaml.org,2002:js/undefined> ''
  moodText:
    Angry: 19788
    Unhappy: 19789
    Neutral: 19790
    Happy: 19791
    Euphoric: 19792
