guid: 112091
desc: 163059
icon: data/ui/2kimages/main/3dicons/icon_resident.png
name: residence_arctic_tier01
id: !<tag:yaml.org,2002:js/undefined> ''
template: ResidenceBuilding7_Arctic
building:
  type: Residence
  category: 100004
  terrain: Terrain
  regions:
    - Arctic
  pickingAsset: 112091
cost:
  costs:
    '1010196': 2
  influenceCostType: None
  influenceCostPoints: 1
upgradable:
  next: 112652
  costs:
    '1010196': 4
residence7:
  populationLevel7: 112642
  start: 1
  max: 10
