guid: 1010200
desc: 11737
icon: data/ui/2kimages/main/3dicons/icon_fish.png
name: fish
id: !<tag:yaml.org,2002:js/undefined> ''
template: Product
product:
  category: 11704
  regions:
    - Moderate
    - Colony01
  civLevel: 1
  storageLevel: Building
  color: !<tag:yaml.org,2002:js/undefined> ''
  basePrice: 20
  pathLayer: Street
  deltaOnly: !<tag:yaml.org,2002:js/undefined> ''
  isWorkforce: !<tag:yaml.org,2002:js/undefined> ''
  isStrategicResource: !<tag:yaml.org,2002:js/undefined> ''
  isAbstract: !<tag:yaml.org,2002:js/undefined> ''
  canBeNegative: !<tag:yaml.org,2002:js/undefined> ''
