guid: 1010216
desc: 11754
icon: data/ui/2kimages/main/3dicons/icon_schnapps_4.png
name: schnapps
id: !<tag:yaml.org,2002:js/undefined> ''
template: Product
product:
  category: 11705
  regions:
    - Moderate
  civLevel: 1
  storageLevel: Building
  color: !<tag:yaml.org,2002:js/undefined> ''
  basePrice: 25
  pathLayer: Street
  deltaOnly: !<tag:yaml.org,2002:js/undefined> ''
  isWorkforce: !<tag:yaml.org,2002:js/undefined> ''
  isStrategicResource: !<tag:yaml.org,2002:js/undefined> ''
  isAbstract: !<tag:yaml.org,2002:js/undefined> ''
  canBeNegative: !<tag:yaml.org,2002:js/undefined> ''
