guid: 1010117
desc: 0
icon: data/ui/2kimages/main/icons/icon_resource_craftspeople.png
name: moderate workforce 4
id: !<tag:yaml.org,2002:js/undefined> ''
template: Product
product:
  category: 0
  regions: !<tag:yaml.org,2002:js/undefined> ''
  civLevel: !<tag:yaml.org,2002:js/undefined> ''
  storageLevel: Area
  color: !<tag:yaml.org,2002:js/undefined> ''
  basePrice: !<tag:yaml.org,2002:js/undefined> ''
  pathLayer: Street
  deltaOnly: true
  isWorkforce: true
  isStrategicResource: !<tag:yaml.org,2002:js/undefined> ''
  isAbstract: !<tag:yaml.org,2002:js/undefined> ''
  canBeNegative: !<tag:yaml.org,2002:js/undefined> ''
