guid: 1010218
desc: 11757
icon: data/ui/2kimages/main/3dicons/icon_beams.png
name: beams
id: ProductBeams
template: Product
product:
  category: 11707
  regions:
    - Moderate
  civLevel: 2
  storageLevel: Building
  color: !<tag:yaml.org,2002:js/undefined> ''
  basePrice: 73
  pathLayer: Street
  deltaOnly: !<tag:yaml.org,2002:js/undefined> ''
  isWorkforce: !<tag:yaml.org,2002:js/undefined> ''
  isStrategicResource: !<tag:yaml.org,2002:js/undefined> ''
  isAbstract: !<tag:yaml.org,2002:js/undefined> ''
  canBeNegative: !<tag:yaml.org,2002:js/undefined> ''
