guid: 1010348
desc: 0
icon: data/ui/2kimages/main/3dicons/icon_box_arena.png
name: Boxing Arena
id: !<tag:yaml.org,2002:js/undefined> ''
template: Product
product:
  category: 11709
  regions:
    - Colony01
  civLevel: !<tag:yaml.org,2002:js/undefined> ''
  storageLevel: Building
  color: ff51cfcc
  basePrice: !<tag:yaml.org,2002:js/undefined> ''
  pathLayer: Street
  deltaOnly: !<tag:yaml.org,2002:js/undefined> ''
  isWorkforce: !<tag:yaml.org,2002:js/undefined> ''
  isStrategicResource: !<tag:yaml.org,2002:js/undefined> ''
  isAbstract: true
  canBeNegative: !<tag:yaml.org,2002:js/undefined> ''
