guid: 1010232
desc: 11738
icon: data/ui/2kimages/main/3dicons/icon_niter.png
name: salpeter
id: !<tag:yaml.org,2002:js/undefined> ''
template: Product
product:
  category: 11702
  regions:
    - Colony01
  civLevel: 5
  storageLevel: Building
  color: !<tag:yaml.org,2002:js/undefined> ''
  basePrice: 1000
  pathLayer: Street
  deltaOnly: !<tag:yaml.org,2002:js/undefined> ''
  isWorkforce: !<tag:yaml.org,2002:js/undefined> ''
  isStrategicResource: !<tag:yaml.org,2002:js/undefined> ''
  isAbstract: !<tag:yaml.org,2002:js/undefined> ''
  canBeNegative: !<tag:yaml.org,2002:js/undefined> ''
