guid: 1010566
desc: 11793
icon: data/ui/2kimages/main/3dicons/icon_oil.png
name: oil
id: ProductOil
template: Product
product:
  category: 11797
  regions: !<tag:yaml.org,2002:js/undefined> ''
  civLevel: 4
  storageLevel: Building
  color: !<tag:yaml.org,2002:js/undefined> ''
  basePrice: 4
  pathLayer: Railway
  deltaOnly: !<tag:yaml.org,2002:js/undefined> ''
  isWorkforce: !<tag:yaml.org,2002:js/undefined> ''
  isStrategicResource: true
  isAbstract: !<tag:yaml.org,2002:js/undefined> ''
  canBeNegative: !<tag:yaml.org,2002:js/undefined> ''
