guid: 1010196
desc: 11742
icon: data/ui/2kimages/main/3dicons/icon_wooden_planks.png
name: timber
id: ProductTimber
template: Product
product:
  category: 11707
  regions:
    - Moderate
    - Colony01
  civLevel: 1
  storageLevel: Building
  color: !<tag:yaml.org,2002:js/undefined> ''
  basePrice: 5
  pathLayer: Street
  deltaOnly: !<tag:yaml.org,2002:js/undefined> ''
  isWorkforce: !<tag:yaml.org,2002:js/undefined> ''
  isStrategicResource: !<tag:yaml.org,2002:js/undefined> ''
  isAbstract: !<tag:yaml.org,2002:js/undefined> ''
  canBeNegative: !<tag:yaml.org,2002:js/undefined> ''
