guid: 112697
desc: 117254
icon: data/ui/2kimages/main/3dicons/icon_goose_feathers.png
name: goose feathers
id: !<tag:yaml.org,2002:js/undefined> ''
template: Product
product:
  category: 11702
  regions:
    - Arctic
  civLevel: 1
  storageLevel: Building
  color: !<tag:yaml.org,2002:js/undefined> ''
  basePrice: 60
  pathLayer: Street
  deltaOnly: !<tag:yaml.org,2002:js/undefined> ''
  isWorkforce: !<tag:yaml.org,2002:js/undefined> ''
  isStrategicResource: !<tag:yaml.org,2002:js/undefined> ''
  isAbstract: !<tag:yaml.org,2002:js/undefined> ''
  canBeNegative: !<tag:yaml.org,2002:js/undefined> ''
