guid: 112708
desc: 0
icon: data/ui/2kimages/main/3dicons/icon_heating_center.png
name: heat from heater
id: ServiceHeat
template: Product
product:
  category: 11702
  regions:
    - Arctic
  civLevel: !<tag:yaml.org,2002:js/undefined> ''
  storageLevel: Building
  color: ff51cfcc
  basePrice: !<tag:yaml.org,2002:js/undefined> ''
  pathLayer: Street
  deltaOnly: !<tag:yaml.org,2002:js/undefined> ''
  isWorkforce: !<tag:yaml.org,2002:js/undefined> ''
  isStrategicResource: !<tag:yaml.org,2002:js/undefined> ''
  isAbstract: true
  canBeNegative: !<tag:yaml.org,2002:js/undefined> ''
