guid: 120008
desc: 11731
icon: data/ui/2kimages/main/3dicons/icon_wood_log.png
name: wood
id: !<tag:yaml.org,2002:js/undefined> ''
template: Product
product:
  category: 11702
  regions:
    - Moderate
    - Colony01
  civLevel: 1
  storageLevel: Building
  color: !<tag:yaml.org,2002:js/undefined> ''
  basePrice: 3
  pathLayer: Street
  deltaOnly: !<tag:yaml.org,2002:js/undefined> ''
  isWorkforce: !<tag:yaml.org,2002:js/undefined> ''
  isStrategicResource: !<tag:yaml.org,2002:js/undefined> ''
  isAbstract: !<tag:yaml.org,2002:js/undefined> ''
  canBeNegative: !<tag:yaml.org,2002:js/undefined> ''
