guid: 120021
desc: 11765
icon: data/ui/2kimages/main/3dicons/icon_coal.png
name: stone coal
id: !<tag:yaml.org,2002:js/undefined> ''
template: Product
product:
  category: 11797
  regions: !<tag:yaml.org,2002:js/undefined> ''
  civLevel: !<tag:yaml.org,2002:js/undefined> ''
  storageLevel: Building
  color: !<tag:yaml.org,2002:js/undefined> ''
  basePrice: 1
  pathLayer: Railway
  deltaOnly: !<tag:yaml.org,2002:js/undefined> ''
  isWorkforce: !<tag:yaml.org,2002:js/undefined> ''
  isStrategicResource: true
  isAbstract: !<tag:yaml.org,2002:js/undefined> ''
  canBeNegative: !<tag:yaml.org,2002:js/undefined> ''
