guid: 120022
desc: 12473
icon: data/ui/2kimages/main/3dicons/icon_electricity.png
name: electricity
id: ProductElectricity
template: Product
product:
  category: 0
  regions: !<tag:yaml.org,2002:js/undefined> ''
  civLevel: !<tag:yaml.org,2002:js/undefined> ''
  storageLevel: Area
  color: !<tag:yaml.org,2002:js/undefined> ''
  basePrice: !<tag:yaml.org,2002:js/undefined> ''
  pathLayer: Street
  deltaOnly: true
  isWorkforce: !<tag:yaml.org,2002:js/undefined> ''
  isStrategicResource: !<tag:yaml.org,2002:js/undefined> ''
  isAbstract: true
  canBeNegative: !<tag:yaml.org,2002:js/undefined> ''
