guid: 1010346
desc: 163059
icon: data/ui/2kimages/main/3dicons/icon_resident.png
name: residence_tier04
id: !<tag:yaml.org,2002:js/undefined> ''
template: ResidenceBuilding7
building:
  type: Residence
  category: 100004
  terrain: Terrain
  regions:
    - Moderate
  pickingAsset: 1010343
cost:
  costs:
    '1010196': 8
    '1010205': 10
    '1010207': 8
    '1010218': 8
  influenceCostType: None
  influenceCostPoints: 1
upgradable:
  next: 1010347
  costs:
    '1010196': 10
    '1010202': 3
    '1010205': 4
    '1010207': 3
    '1010218': 3
residence7:
  populationLevel7: 15000003
  start: 1
  max: 40
