guid: 1010347
desc: 163059
icon: data/ui/2kimages/main/3dicons/icon_resident.png
name: residence_tier05
id: !<tag:yaml.org,2002:js/undefined> ''
template: ResidenceBuilding7
building:
  type: Residence
  category: 100004
  terrain: Terrain
  regions:
    - Moderate
  pickingAsset: 1010343
cost:
  costs:
    '1010196': 10
    '1010202': 10
    '1010205': 15
    '1010207': 10
    '1010218': 12
  influenceCostType: None
  influenceCostPoints: 1
upgradable:
  next: 0
  costs: !<tag:yaml.org,2002:js/undefined> ''
residence7:
  populationLevel7: 15000004
  start: 1
  max: 50
