guid: 1010345
desc: 163059
icon: data/ui/2kimages/main/3dicons/icon_resident.png
name: residence_tier03
id: !<tag:yaml.org,2002:js/undefined> ''
template: ResidenceBuilding7
building:
  type: Residence
  category: 100004
  terrain: Terrain
  regions:
    - Moderate
  pickingAsset: 1010343
cost:
  costs:
    '1010196': 8
    '1010205': 5
    '1010218': 4
  influenceCostType: None
  influenceCostPoints: 1
upgradable:
  next: 1010346
  costs:
    '1010196': 8
    '1010205': 3
    '1010207': 2
    '1010218': 2
residence7:
  populationLevel7: 15000002
  start: 1
  max: 30
