guid: 101255
desc: !<tag:yaml.org,2002:js/undefined> ''
icon: !<tag:yaml.org,2002:js/undefined> ''
name: residence_colony01_tier02
id: !<tag:yaml.org,2002:js/undefined> ''
template: ResidenceBuilding7
