guid: 101255
desc: 163059
icon: data/ui/2kimages/main/3dicons/icon_resident.png
name: residence_colony01_tier02
id: !<tag:yaml.org,2002:js/undefined> ''
template: ResidenceBuilding7
building:
  type: Residence
  category: 100004
  terrain: Terrain
  regions:
    - Colony01
  pickingAsset: 101254
cost:
  costs:
    '1010196': 2
  influenceCostType: None
  influenceCostPoints: 1
upgradable:
  next: 0
  costs:
    '1010196': 6
    '1010205': 2
    '1010218': 2
residence7:
  populationLevel7: 15000006
  start: 1
  max: 20
